'use client';

import { useState } from 'react';
import { MainLayout } from '@/components/layout/main-layout';
import { Button } from '@/components/ui/button';
import { Download, FileText, Loader2, CheckCircle } from 'lucide-react';

const reports = [
  {
    title: 'Executive Risk Summary',
    description: 'Board-level quantum cryptographic risk assessment',
    date: '2025-02-28',
    size: '2.4 MB',
  },
  {
    title: 'Detailed Asset Audit',
    description: 'Complete inventory with migration recommendations',
    date: '2025-02-28',
    size: '8.7 MB',
  },
  {
    title: 'Compliance Report',
    description: 'NIST post-quantum cryptography guidelines alignment',
    date: '2025-02-27',
    size: '1.2 MB',
  },
  {
    title: 'Migration Roadmap',
    description: 'Phased transition plan with timelines and dependencies',
    date: '2025-02-26',
    size: '3.1 MB',
  },
];

// Generate a PDF-like content and trigger download
function generateAndDownloadPDF(report: typeof reports[0]) {
  const currentDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // Build report content based on report type
  let reportContent = '';

  if (report.title === 'Executive Risk Summary') {
    reportContent = `
QUANTUMSHIELD - EXECUTIVE RISK SUMMARY
${'='.repeat(60)}
Generated: ${currentDate}
Classification: CONFIDENTIAL
${'='.repeat(60)}

1. EXECUTIVE OVERVIEW
${'-'.repeat(40)}
This report provides a board-level assessment of your organization's 
exposure to quantum computing threats targeting current cryptographic 
infrastructure.

Overall Risk Score: 7.8 / 10 (HIGH)
Total Systems Assessed: 12,438
Critical Vulnerabilities: 3,247 systems
Estimated Time to Quantum Threat: 5-10 years

2. KEY FINDINGS
${'-'.repeat(40)}
• 3,247 systems use RSA-2048, which is vulnerable to Shor's algorithm
• 847 high-sensitivity assets with 20+ year data retention at harvest risk
• 2,140 systems use ECC-P256, requiring migration to post-quantum alternatives
• 12 critical infrastructure dependencies need immediate migration planning
• Current migration coverage: 23% of total cryptographic assets

3. RISK BREAKDOWN BY ALGORITHM
${'-'.repeat(40)}
Algorithm       | Systems | Risk Level | Migration Priority
RSA-2048        | 3,247   | CRITICAL   | Immediate
ECC-P256        | 2,140   | HIGH       | Q4 2025
RSA-4096        | 1,804   | MEDIUM     | Q2 2026
AES-256         | 3,412   | LOW        | Monitor
Post-Quantum    | 1,835   | SAFE       | N/A

4. HARVEST NOW, DECRYPT LATER (HNDL) RISK
${'-'.repeat(40)}
Data Sensitivity    | Assets at Risk | Estimated Value
Top Secret          | 127            | $2.3B
Confidential        | 384            | $890M  
Internal            | 1,247          | $340M
Public              | 2,890          | $12M

5. RECOMMENDED ACTIONS
${'-'.repeat(40)}
Priority 1 (Immediate):
  - Begin RSA-2048 to Kyber-1024 migration for internet-facing systems
  - Implement hybrid TLS for all customer-facing APIs
  - Rotate all SSH keys to post-quantum algorithms

Priority 2 (Within 6 months):
  - Migrate ECC-P256 to Dilithium + ECC-P521 hybrid
  - Update database encryption to AES-256-GCM
  - Deploy quantum-safe VPN tunnels

Priority 3 (Within 12 months):
  - Complete RSA-4096 to Falcon-1024 migration  
  - Update code signing infrastructure
  - Full post-quantum PKI deployment

6. BUDGET ESTIMATION
${'-'.repeat(40)}
Phase 1: $1.2M - $1.8M (tooling, training, initial migration)
Phase 2: $800K - $1.2M (continued migration, testing)
Phase 3: $500K - $900K (completion, validation, audit)
Total Estimated: $2.5M - $3.9M

${'='.repeat(60)}
Report generated by QuantumShield v2.1
© 2025 QuantumShield. All rights reserved.
`;
  } else if (report.title === 'Detailed Asset Audit') {
    reportContent = `
QUANTUMSHIELD - DETAILED ASSET AUDIT REPORT
${'='.repeat(60)}
Generated: ${currentDate}
Classification: CONFIDENTIAL
${'='.repeat(60)}

1. AUDIT SCOPE
${'-'.repeat(40)}
Total Assets Scanned: 12,438
Scan Duration: 4 hours 23 minutes
Last Full Scan: ${currentDate}
Coverage: 100% of registered assets

2. ASSET INVENTORY BY TYPE
${'-'.repeat(40)}
Type                | Count  | Avg Risk Score
Load Balancers      | 847    | 7.2
Databases           | 1,234  | 8.1
Application Servers | 3,456  | 6.8
Cache Systems       | 892    | 5.4
Storage Systems     | 2,345  | 4.2
Network Devices     | 1,678  | 7.5
IoT/Embedded        | 986    | 8.9
Other               | 1,000  | 5.1

3. CRITICAL ASSETS DETAIL
${'-'.repeat(40)}

ASSET-001: api-gateway-prod
  Type: Load Balancer | Region: us-east-1
  Algorithm: RSA-2048 | Key Length: 2048 bits
  Risk Score: 8.7/10 | Sensitivity: Critical
  Exposure: Internet | Retention: 7 years
  Dependencies: db-cluster-1, cache-redis-1
  Recommendation: IMMEDIATE migration to Kyber-1024

ASSET-002: db-cluster-1  
  Type: Database | Region: us-east-1
  Algorithm: ECC-256 | Key Length: 256 bits
  Risk Score: 9.2/10 | Sensitivity: Critical
  Exposure: Internal | Retention: 20+ years
  Dependencies: None
  Recommendation: Migrate to Dilithium by Q4 2025

ASSET-003: cache-redis-1
  Type: Cache | Region: us-west-2
  Algorithm: RSA-4096 | Key Length: 4096 bits
  Risk Score: 6.1/10 | Sensitivity: High
  Exposure: Internal | Retention: 5 years
  Dependencies: None
  Recommendation: Plan migration to Falcon-1024

ASSET-004: backup-archive-001
  Type: Storage | Region: us-east-1
  Algorithm: AES-256 | Key Length: 256 bits
  Risk Score: 4.2/10 | Sensitivity: High
  Exposure: Offline | Retention: 20+ years
  Dependencies: None
  Recommendation: Monitor - AES-256 is quantum-safe

ASSET-005: ssh-bastion-prod
  Type: Bastion Host | Region: eu-west-1
  Algorithm: RSA-2048 | Key Length: 2048 bits
  Risk Score: 7.8/10 | Sensitivity: Medium
  Exposure: Internet | Retention: 3 years
  Dependencies: None
  Recommendation: IMMEDIATE key rotation to PQC

4. ALGORITHM DISTRIBUTION
${'-'.repeat(40)}
RSA-2048:   ████████████████████  26.1% (3,247 assets)
ECC-P256:   █████████████         17.2% (2,140 assets)
RSA-4096:   ███████████           14.5% (1,804 assets)
AES-256:    ████████████████████████████ 27.4% (3,412 assets)
PQC:        ███████████           14.8% (1,835 assets)

5. REGIONAL BREAKDOWN
${'-'.repeat(40)}
Region      | Assets | Critical | Avg Score
us-east-1   | 4,523  | 1,234    | 7.1
us-west-2   | 2,890  | 678      | 6.5
eu-west-1   | 2,345  | 892      | 7.8
ap-south-1  | 1,456  | 234      | 5.9
ap-east-1   | 1,224  | 209      | 6.2

${'='.repeat(60)}
Report generated by QuantumShield v2.1
© 2025 QuantumShield. All rights reserved.
`;
  } else if (report.title === 'Compliance Report') {
    reportContent = `
QUANTUMSHIELD - COMPLIANCE REPORT
${'='.repeat(60)}
Generated: ${currentDate}
Framework: NIST Post-Quantum Cryptography Standards
Classification: CONFIDENTIAL
${'='.repeat(60)}

1. COMPLIANCE OVERVIEW
${'-'.repeat(40)}
Overall Compliance Score: 62% (In Progress)
Target Compliance Date: Q4 2026
Standards Referenced:
  - NIST SP 800-208 (Stateful Hash-Based Signatures)
  - NIST FIPS 203 (ML-KEM / Kyber)
  - NIST FIPS 204 (ML-DSA / Dilithium)
  - NIST FIPS 205 (SLH-DSA / SPHINCS+)

2. COMPLIANCE BY CATEGORY
${'-'.repeat(40)}

Category                        | Status      | Score
Cryptographic Inventory         | ✅ Complete  | 95%
Risk Assessment                 | ✅ Complete  | 88%
Migration Planning              | 🔶 Partial  | 65%
Algorithm Implementation        | 🔶 Partial  | 45%
Key Management Updates          | ⚠️ Started  | 30%
Testing & Validation            | ⚠️ Started  | 25%
Production Deployment           | ❌ Not Started | 0%
Documentation & Training        | 🔶 Partial  | 55%

3. NIST FIPS 203 (ML-KEM) COMPLIANCE
${'-'.repeat(40)}
Requirement                     | Status
Algorithm supported             | ✅ Yes (Kyber-512, 768, 1024)
Key generation tested           | ✅ Passed
Encapsulation/Decapsulation     | ✅ Passed  
Performance benchmarked         | ✅ Completed
Integration with TLS 1.3        | 🔶 In Progress
Hardware acceleration           | ⚠️ Pending
Production deployment           | ❌ Not Started

4. NIST FIPS 204 (ML-DSA) COMPLIANCE
${'-'.repeat(40)}
Requirement                     | Status
Algorithm supported             | ✅ Yes (Dilithium-2, 3, 5)
Signature generation tested     | ✅ Passed
Signature verification tested   | ✅ Passed
Certificate chain support       | 🔶 In Progress
Code signing integration        | ⚠️ Pending
HSM support                     | ⚠️ Pending

5. GAP ANALYSIS
${'-'.repeat(40)}
• 38% of cryptographic assets not yet assessed for PQC migration
• Key management systems need firmware updates for PQC support
• 5 third-party integrations lack PQC support — vendor engagement required
• Training program needed for 45 engineering team members
• Disaster recovery procedures not updated for PQC algorithms

6. REMEDIATION TIMELINE
${'-'.repeat(40)}
Q1 2025: Complete algorithm support and testing ✅
Q2 2025: Begin production hybrid deployment
Q3 2025: Migrate 50% of critical systems
Q4 2025: Complete ECC-P256 migration
Q1 2026: Complete RSA-2048 migration
Q2 2026: Complete all migrations, final audit

${'='.repeat(60)}
Report generated by QuantumShield v2.1
© 2025 QuantumShield. All rights reserved.
`;
  } else {
    reportContent = `
QUANTUMSHIELD - MIGRATION ROADMAP
${'='.repeat(60)}
Generated: ${currentDate}
Classification: CONFIDENTIAL  
${'='.repeat(60)}

1. MIGRATION OVERVIEW
${'-'.repeat(40)}
Total Migration Paths: 3
Systems Requiring Migration: 7,191
Estimated Total Duration: 18 months
Budget Allocation: $3.2M

2. PATH 1: RSA-2048 → Kyber-1024 + RSA-4096
${'-'.repeat(40)}
Priority: CRITICAL | Systems: 3,247 | Timeline: Immediate

Phase 1: Assessment & Planning (2 weeks)
  [✅] Inventory all RSA-2048 certificates and keys
  [✅] Map dependencies between systems  
  [✅] Identify critical path systems
  [✅] Create rollback procedures

Phase 2: Development Environment (4 weeks)
  [🔶] Deploy Kyber-1024 in dev/staging environments
  [🔶] Update TLS configurations for hybrid mode
  [  ] Run compatibility tests
  [  ] Performance benchmarking

Phase 3: Staged Rollout (6 weeks)
  [  ] Migrate internal APIs first
  [  ] Update load balancer certificates
  [  ] Migrate customer-facing endpoints by region
  [  ] Monitor for handshake failures

Phase 4: Validation & Cleanup (2 weeks)
  [  ] Verify all systems using PQC
  [  ] Remove legacy RSA-2048 key material
  [  ] Update compliance documentation
  [  ] Final security audit

3. PATH 2: ECC-P256 → Dilithium + ECC-P521
${'-'.repeat(40)}
Priority: HIGH | Systems: 2,140 | Timeline: Q4 2025

Phase 1: Algorithm Evaluation (3 weeks)
  [🔶] Evaluate Dilithium variants
  [  ] Test signature sizes
  [  ] Assess PKI impact
  [  ] Plan hybrid deployment

Phase 2: Infrastructure Updates (5 weeks)
  [  ] Update HSMs for Dilithium support
  [  ] Modify certificate issuance
  [  ] Deploy hybrid signing
  [  ] Validate integrations

Phase 3: Production Migration (8 weeks)
  [  ] Migrate code signing first
  [  ] Update API authentication
  [  ] Roll out to databases
  [  ] Parallel run old/new

Phase 4: Decommission Legacy (3 weeks)
  [  ] Phase out ECC-P256
  [  ] Rotate remaining keys
  [  ] Archive compliance evidence
  [  ] Update DR procedures

4. PATH 3: RSA-4096 → Falcon-1024 + RSA-6144
${'-'.repeat(40)}
Priority: MEDIUM | Systems: 1,804 | Timeline: Q2 2026

Phase 1: Planning (2 weeks)
Phase 2: Pilot Deployment (6 weeks)  
Phase 3: Gradual Migration (10 weeks)
Phase 4: Completion (3 weeks)

5. DEPENDENCY MAP
${'-'.repeat(40)}
api-gateway ──→ db-cluster-1 ──→ backup-archive
     │                │
     ▼                ▼
cache-redis     auth-service ──→ identity-provider
     │                │
     ▼                ▼
cdn-proxy       key-vault ──→ cert-manager

6. RISK MATRIX
${'-'.repeat(40)}
Risk                              | Impact | Probability | Mitigation
Client TLS compatibility          | High   | Medium      | Hybrid mode
Increased handshake latency       | Medium | High        | Performance tuning
HSM firmware downtime             | High   | Low         | Rolling updates
Third-party API compat            | Medium | Medium      | Vendor engagement
Key size storage impact           | Low    | High        | Storage expansion

7. SUCCESS METRICS
${'-'.repeat(40)}
• 100% of critical systems migrated to PQC by Q4 2025
• Zero unplanned downtime during migration
• < 5% performance degradation in hybrid mode
• Full NIST compliance by Q2 2026
• All team members trained on PQC by Q3 2025

${'='.repeat(60)}
Report generated by QuantumShield v2.1
© 2025 QuantumShield. All rights reserved.
`;
  }

  // Create and download the file as a text-based PDF
  const blob = new Blob([reportContent], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `QuantumShield_${report.title.replace(/\s+/g, '_')}_${report.date}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export default function ReportsPage() {
  const [downloadingIdx, setDownloadingIdx] = useState<number | null>(null);
  const [downloadedIdx, setDownloadedIdx] = useState<Set<number>>(new Set());

  const handleDownload = async (report: typeof reports[0], idx: number) => {
    setDownloadingIdx(idx);
    // Simulate a small delay for UX
    await new Promise(resolve => setTimeout(resolve, 800));
    generateAndDownloadPDF(report);
    setDownloadingIdx(null);
    setDownloadedIdx(prev => new Set(prev).add(idx));

    // Reset the downloaded state after 3 seconds
    setTimeout(() => {
      setDownloadedIdx(prev => {
        const next = new Set(prev);
        next.delete(idx);
        return next;
      });
    }, 3000);
  };

  return (
    <MainLayout>
      <div className="space-y-6">
        <div className="space-y-2">
          <h1 className="text-3xl font-bold text-foreground">Reports & Exports</h1>
          <p className="text-muted-foreground">Generate and download executive reports and detailed audits</p>
        </div>

        <div className="space-y-3">
          {reports.map((report, idx) => (
            <div key={idx} className="border border-border rounded-lg bg-card p-4 hover:border-primary/50 transition-colors">
              <div className="flex items-start justify-between">
                <div className="flex items-start gap-3 flex-1">
                  <FileText className="w-5 h-5 text-primary flex-shrink-0 mt-0.5" />
                  <div>
                    <h3 className="text-sm font-semibold text-foreground">{report.title}</h3>
                    <p className="text-xs text-muted-foreground">{report.description}</p>
                    <p className="text-xs text-muted-foreground mt-1">Generated: {report.date} • {report.size}</p>
                  </div>
                </div>
                <Button
                  size="sm"
                  className={`h-8 px-3 text-xs flex-shrink-0 transition-all duration-300 ${downloadedIdx.has(idx)
                      ? 'bg-green-600 hover:bg-green-700 text-white'
                      : 'bg-primary hover:bg-primary/90 text-primary-foreground'
                    }`}
                  disabled={downloadingIdx === idx}
                  onClick={() => handleDownload(report, idx)}
                >
                  {downloadingIdx === idx ? (
                    <>
                      <Loader2 className="w-3 h-3 mr-1 animate-spin" />
                      Generating...
                    </>
                  ) : downloadedIdx.has(idx) ? (
                    <>
                      <CheckCircle className="w-3 h-3 mr-1" />
                      Downloaded
                    </>
                  ) : (
                    <>
                      <Download className="w-3 h-3 mr-1" />
                      PDF
                    </>
                  )}
                </Button>
              </div>
            </div>
          ))}
        </div>

        <div className="border border-border rounded-lg bg-card p-4 space-y-3">
          <h3 className="text-sm font-semibold text-foreground uppercase tracking-wider">Generate New Report</h3>
          <select className="w-full h-9 px-3 rounded bg-secondary border border-border text-sm text-foreground">
            <option>Select report type...</option>
            <option>Executive Summary</option>
            <option>Technical Assessment</option>
            <option>Migration Plan</option>
            <option>Compliance Checklist</option>
          </select>
          <Button className="w-full bg-primary hover:bg-primary/90 text-primary-foreground">
            Generate Report
          </Button>
        </div>
      </div>
    </MainLayout>
  );
}
